In [18]:
import pandas as pd
import numpy as np

## Ejercicios

#### 1. Leer los datos del fichero Fullmetadata.csv y almacenarlo en un DataFrame

In [19]:
datos = pd.DataFrame()
datos = pd.read_csv("/home/manu/Desktop/Test/data/Fullmetadata.cvs", index_col="player_id") 
datos.head()

,player_name,games,time,goals,shots,key_passes,yellow_cards,red_cards,position,team_name
player_id,,,,,,,,,,
8865,Ollie Watkins,9,810,6,22,12,0,0,F,Aston Villa
675,Jack Grealish,9,810,5,26,26,2,0,F M,Aston Villa
592,Ross Barkley,6,454,2,17,15,0,0,M,Aston Villa
1024,Tyrone Mings,9,810,2,7,2,2,0,D,Aston Villa
7726,Ezri Konsa Ngoyo,9,810,2,7,0,0,0,D,Aston Villa

#### 2. Elimina la columna games sin crear nuevo DataFrame

In [20]:
del datos["games"]
datos.head()

,player_name,time,goals,shots,key_passes,yellow_cards,red_cards,position,team_name
player_id,,,,,,,,,
8865,Ollie Watkins,810,6,22,12,0,0,F,Aston Villa
675,Jack Grealish,810,5,26,26,2,0,F M,Aston Villa
592,Ross Barkley,454,2,17,15,0,0,M,Aston Villa
1024,Tyrone Mings,810,2,7,2,2,0,D,Aston Villa
7726,Ezri Konsa Ngoyo,810,2,7,0,0,0,D,Aston Villa

#### 3. Selecciona los jugadores del AstonVilla

In [21]:
datos[(datos["team_name"] == "Aston Villa")].head()

,player_name,time,goals,shots,key_passes,yellow_cards,red_cards,position,team_name
player_id,,,,,,,,,
8865,Ollie Watkins,810,6,22,12,0,0,F,Aston Villa
675,Jack Grealish,810,5,26,26,2,0,F M,Aston Villa
592,Ross Barkley,454,2,17,15,0,0,M,Aston Villa
1024,Tyrone Mings,810,2,7,2,2,0,D,Aston Villa
7726,Ezri Konsa Ngoyo,810,2,7,0,0,0,D,Aston Villa

#### 4. Selecciona los jugadores que hayan sido expulsados

In [22]:
datos[(datos["red_cards"] != 0)].head()

,player_name,time,goals,shots,key_passes,yellow_cards,red_cards,position,team_name
player_id,,,,,,,,,
6026,Richarlison,642,1,25,10,1,1,F,Everton
1823,Lucas Digne,703,0,3,15,0,1,D,Everton
7153,Matheus Pereira,795,1,17,22,1,1,M,West Bromwich Albion
545,Kieran Gibbs,135,0,0,1,0,1,D,West Bromwich Albion
5549,Luka Milivojevic,311,0,3,4,1,1,M S,Crystal Palace

#### 5. Selecciona los jugadores que hayan visto una tarjeta amarilla pero no hayan sido expulsados

In [23]:
datos[(datos["yellow_cards"] != 0) & (datos["red_cards"] == 0)].head()

,player_name,time,goals,shots,key_passes,yellow_cards,red_cards,position,team_name
player_id,,,,,,,,,
675,Jack Grealish,810,5,26,26,2,0,F M,Aston Villa
1024,Tyrone Mings,810,2,7,2,2,0,D,Aston Villa
7723,John McGinn,810,1,10,15,3,0,M,Aston Villa
884,Matt Targett,810,0,3,9,3,0,D,Aston Villa
6122,Douglas Luiz,789,0,8,8,2,0,M,Aston Villa