In [35]:
import numpy as np
import pandas as pd

### Indexaciónde dataframes

##### La indexación nos permite seleccionar valores de una Serio o Dataframe

In [36]:
# Creamos una lista con los números pares del o al 20
serie_pares = [x for x in range(20) if (x % 2)==0]
serie_pares

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [37]:
# Accedemos al valor en la posición [5] de la lista
serie_pares[5]

10

In [38]:
# Accedemos a las cuatro primeras posiciones de la lista, desde la 0 hasta la anterior a la 5
serie_pares[0:5]

[0, 2, 4, 6, 8]

In [39]:
# Accedemos a la última posición de la lista
serie_pares[-1]

18

In [40]:
# Accedemos desde la posición 3 hasta la última
serie_pares[3:]

[6, 8, 10, 12, 14, 16, 18]

In [41]:
# Creamos un DataFrame con números pares e impares
numeros = pd.DataFrame({
    "pares": list(range(0, 20, 2))
    ,"impares": list(range(1, 20, 2))
})
numeros

   pares  impares
0      0        1
1      2        3
2      4        5
3      6        7
4      8        9
5     10       11
6     12       13
7     14       15
8     16       17
9     18       19

In [42]:
# Indexación mediante clave
numeros.pares

0     0
1     2
2     4
3     6
4     8
5    10
6    12
7    14
8    16
9    18
Name: pares, dtype: int64

In [43]:
# Indexación directa
numeros["pares"]

0     0
1     2
2     4
3     6
4     8
5    10
6    12
7    14
8    16
9    18
Name: pares, dtype: int64

In [44]:
# Indexación directa imprimiendo el nombre de la columna
numeros[["pares"]]

   pares
0      0
1      2
2      4
3      6
4      8
5     10
6     12
7     14
8     16
9     18

#### Indexación mediante el método .loc[]
##### Con el método .loc podemos seleccionar una fila, una columna, un valor o unr ango de valores usando claves

In [45]:
dataframe = pd.DataFrame(np.arange(16).reshape(4, 4),
                         index=["f1","f2","f3","f4",],
                         columns=["c1","c2","c3","c4",])
dataframe

    c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

In [46]:
# Accedemos al la fila f1
dataframe.loc["f1"]

c1    0
c2    1
c3    2
c4    3
Name: f1, dtype: int64

In [47]:
# Si sustituimos una de las etiquetas por dos puntos, supone seleccionar todos los elementos de ese eje
dataframe.loc[:, "c2"]

f1     1
f2     5
f3     9
f4    13
Name: c2, dtype: int64

In [48]:
# Podemos extraer un único valor usando las etiquetas de fila y columna, en éste orden
dataframe.loc["f3", "c4"]

11

##### Con el método iloc[] indexamos usando enteros

In [49]:
# Nos devuelve la final en el índice 1 (Recordamos que el índice empieza en cero)
dataframe.iloc[1]

c1    4
c2    5
c3    6
c4    7
Name: f2, dtype: int64

In [50]:
# Selecciona todas las filas de la columna con elíndice 1
dataframe.iloc[:,1]

f1     1
f2     5
f3     9
f4    13
Name: c2, dtype: int64

In [51]:
# Selecciona las filas del índice 1 al 2 y columnas del 2 al 3
dataframe.iloc[1:3, 2:4]

    c3  c4
f2   6   7
f3  10  11

##### Indexación mediante filtros booleanos

In [52]:
# Devulve True o False, dependiendo si se cumple la condicion
numeros.pares > 2

0    False
1    False
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
Name: pares, dtype: bool

In [53]:
numeros[numeros.pares>2]

   pares  impares
2      4        5
3      6        7
4      8        9
5     10       11
6     12       13
7     14       15
8     16       17
9     18       19

In [54]:
numeros.iloc[1:4, :][numeros.pares>2]

/tmp/ipykernel_2910/3341242192.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  numeros.iloc[1:4, :][numeros.pares>2]

   pares  impares
2      4        5
3      6        7

##### Asignación en Pandas

In [55]:
# Asignamos valores a una nueva columna
numeros['primos'] = [1, 3, 5, 7, 11, 13, 17, 19, 23, 29]
numeros

   pares  impares  primos
0      0        1       1
1      2        3       3
2      4        5       5
3      6        7       7
4      8        9      11
5     10       11      13
6     12       13      17
7     14       15      19
8     16       17      23
9     18       19      29

In [56]:
# Asigmamos valor a una única celda
numeros.iloc[1,2]= 0
numeros

   pares  impares  primos
0      0        1       1
1      2        3       0
2      4        5       5
3      6        7       7
4      8        9      11
5     10       11      13
6     12       13      17
7     14       15      19
8     16       17      23
9     18       19      29

In [57]:
# Asignamos valor a las celdas de las filas que cumplen la condición en la columna paresn
numeros[numeros.pares>2] = -1
numeros

   pares  impares  primos
0      0        1       1
1      2        3       0
2     -1       -1      -1
3     -1       -1      -1
4     -1       -1      -1
5     -1       -1      -1
6     -1       -1      -1
7     -1       -1      -1
8     -1       -1      -1
9     -1       -1      -1

#### Borrar Columnas

In [58]:
# Borra la columna primos de DataFrame numeros
# Con del se borran los datos del DataFrame original
del numeros['primos']
numeros

   pares  impares
0      0        1
1      2        3
2     -1       -1
3     -1       -1
4     -1       -1
5     -1       -1
6     -1       -1
7     -1       -1
8     -1       -1
9     -1       -1

In [60]:
# Asignamos a numeros todas las filas y columnas, excepto la última columna 
# De ésta manera se modifica el DataFrame original
numeros= numeros.iloc[:, :-1]
numeros

   pares
0      0
1      2
2     -1
3     -1
4     -1
5     -1
6     -1
7     -1
8     -1
9     -1

In [61]:
# Visualiamos dataframe
dataframe

    c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

In [64]:
# Borramos el índice 'c1' que está en las columnas (axis=1)
dataframe.drop('c1', axis=1 )

    c2  c3  c4
f1   1   2   3
f2   5   6   7
f3   9  10  11
f4  13  14  15

In [65]:
# Borramos el índice 'f1' que está en las filas (axis=0)
# Vemos que vuelve a aparecer la columna 'c4', ya que drop, por sí sólo, no borra del origen
dataframe.drop('f1', axis=0)

    c1  c2  c3  c4
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

##### Visualizamos dataframe y vemos que drop no borra los datos del DataFrame origen

In [66]:
# Borramos la columna 'c1' otra vez, pero indicando implace=True en drop
# De ésta manera se borran los datos del DataFrame de origen
dataframe.drop(columns='c1', inplace=True)
dataframe

    c2  c3  c4
f1   1   2   3
f2   5   6   7
f3   9  10  11
f4  13  14  15