### Ejercicios

In [18]:
import pandas as pd
import numpy as np
import matplotlib as plt

##### 1. Calcula la diferencia entre el máximo y el mínimo por fila y por columna aplicando una función al dataframe df

In [19]:
df = pd.DataFrame({'A': [1,2,3,4]
                   , 'B': [10,20,30,40]
                   , 'C': [20,40,60,80]
                   },
                   index=['Row 1', 'Row 2','Row 3', 'Row 4'])
df

       A   B   C
Row 1  1  10  20
Row 2  2  20  40
Row 3  3  30  60
Row 4  4  40  80

In [28]:
def diferencia (x):
    return x.max() - x.min()


df['Dif']= df.apply(diferencia, axis=1)
df

       A   B   C  Dif
Row 1  1  10  20   19
Row 2  2  20  40   38
Row 3  3  30  60   57
Row 4  4  40  80   76

In [39]:
df.loc['Dife'] = df.apply(lambda x:x.max()-x.min(), axis=0)
df

       A   B   C  Dif
Row 1  1  10  20   19
Row 2  2  20  40   38
Row 3  3  30  60   57
Row 4  4  40  80   76
Dife   3  30  60   57

##### 2. Calculala matriz correlación entre Apple y Google

In [47]:
df2 = pd.DataFrame({'Appel': np.random.randint(0, 100, 10),
                    'Google': np.random.randint(0, 100, 10)})
df2

   Appel  Google
0     11      14
1     57      82
2     63       4
3     90      37
4     80      42
5     21      15
6     61      15
7     40      66
8     30       7
9     74      36

In [48]:
correlacion = df2.corr()
correlacion

           Appel    Google
Appel   1.000000  0.285168
Google  0.285168  1.000000